/**
 * Bilingual подписи для админки: English term / Русский перевод.
 * Не использовать на пользовательских страницах (дашборд и т.д.).
 */

export const ADMIN_TERM_LABELS = {
  kieCreditsPerSecond: "Kie credits/sec / Кредиты Kie за секунду",
  kieCreditsTotal: "Kie credits total / Всего кредитов Kie",
  usdPerSecond: "USD/sec / Стоимость в USD за секунду",
  providerCost: "Provider cost / Себестоимость провайдера",
  providerUsdTotal: "Provider USD total / Себестоимость в USD",
  providerKztTotal: "Provider KZT total / Себестоимость в ₸",
  manualClientTokens: "Manual client tokens / Ручная цена в токенах",
  finalClientTokens: "Final client tokens / Итоговое списание токенов",
  autoClientTokens: "Auto client tokens / Авторасчёт токенов",
  clientKztPrice: "Client KZT price / Цена клиента в ₸",
  markupPercent: "Markup % / Наценка %",
  marginKzt: "Margin KZT / Маржа в ₸",
  marginPercent: "Margin % / Маржа в %",
  pricingSchema: "pricingSchema / Схема ценообразования",
  providerCostSchema: "providerCost / Себестоимость провайдера",
  manualOverrides: "manualOverrides / Ручные переопределения цены",
  matrix: "matrix / Таблица цены без видео-референса",
  videoInputMatrix: "videoInputMatrix / Таблица цены с видео-референсом",
  estimate: "estimate / Предварительный расчёт",
  submit: "submit / Запуск генерации",
  payload: "Payload / Данные события (тело)",
  webhook: "webhook / Webhook-уведомление",
  callback: "callback / Обратный вызов",
  taskId: "taskId / ID задачи у провайдера",
  providerTaskId: "providerTaskId / ID задачи у Kie",
  statusEndpoint: "statusEndpoint / Endpoint проверки статуса",
  apiModelId: "apiModelId / ID модели у провайдера",
  endpoint: "endpoint / Endpoint запуска задачи",
  costCredits: "costCredits / Базовая стоимость в токенах",
  realCost: "realCost / Реальная себестоимость",
  settingsSchema: "settingsSchema / Схема настроек модели",
  inputType: "Input type / Тип входных данных",
  resolution: "Resolution / Разрешение",
  duration: "Duration / Длительность",
  model: "Model / Модель",
  provider: "Provider / Провайдер",
  status: "Status / Статус",
  payloadMapping: "payloadMapping / Маппинг payload",
  supportsImageInput:
    "supportsImageInput / Поддерживает изображение на входе",
  supportsVideoInput: "supportsVideoInput / Поддерживает видео на входе",
  supportsNegativePrompt:
    "supportsNegativePrompt / Поддерживает negative prompt",
  supportsSeed: "supportsSeed / Поддерживает seed",
  requestPayload: "Request payload / Тело запроса",
  responsePayload: "Response payload / Ответ провайдера",
  statusCode: "Status code / HTTP статус",
  errorMessage: "Error message / Сообщение об ошибке",
  generationId: "Generation ID / ID генерации",
  createdAt: "Created at / Дата создания",
  webhookEvent: "WebhookEvent / Webhook-событие",
  eventType: "Event type / Тип события",
  processedAt: "Processed at / Когда обработано",
  generation: "Generation / Генерация",
  inputFiles: "Input files / Входные файлы",
  outputFiles: "Output files / Результаты",
  metadata: "Metadata / Метаданные",
  completedAt: "Completed at / Дата завершения",
  defaultCredits: "defaultCredits / Значение по умолчанию (токены)",
  fallbackCredits: "fallbackCredits / Запасное значение (токены)",
  usdToKzt: "usdToKzt / Курс USD→KZT",
  internalTokenValueKzt:
    "internalTokenValueKzt / Стоимость 1 токена в ₸",
  pricingSource: "pricingSource / Источник ценообразования",
  /** Таблица Pricing Studio — заголовки */
  psTableInput: "Input type / Тип входных данных",
  psTableResolution: "Resolution / Разрешение",
  psTableDuration: "Duration / Длительность",
  psTableMarginBadge: "Режим цены / Авто или ручная",
  tokenValueKzt: "Token value KZT / Стоимость токена в ₸",
  userEmail: "User / Пользователь",
  /** Provider monitor */
  providerMonitorTitle: "Providers / Провайдеры",
  providerKie: "Kie.ai",
  balanceKie: "Balance / Баланс Kie",
  lastCheck: "Last check / Последняя проверка",
  checkConnection: "Check connection / Проверить подключение",
  successRate: "Success rate / Процент успеха",
  realGenerations: "Real generations / Реальные генерации",
  storageTitle: "Storage / Хранилище",
  storageMode: "Storage mode / Режим хранения",
  s3Endpoint: "S3 endpoint / Endpoint S3",
  s3Bucket: "S3 bucket / Bucket S3",
  s3Region: "S3 region / Регион S3",
  publicUrl: "Public URL / Публичный URL",
  uploadedFiles: "Uploaded files / Загруженные файлы",
  generatedFiles: "Generated files / Сгенерированные файлы",
  totalSize: "Total size / Общий размер",
  checkStorage: "Check storage / Проверить хранилище",
  checkUrl: "Check URL / Проверить URL",
  configured: "Configured / Настроено",
  missing: "Missing / Не задано",
  localStorage: "Local storage / Локальное хранилище",
  finance: "Finance / Финансы",
  creditTransactions: "Credit Transactions / Транзакции токенов",
  revenue: "Revenue / Доход",
  tokensPurchased: "Tokens purchased / Куплено токенов",
  tokensSpent: "Tokens spent / Потрачено токенов",
  tokensRefunded: "Tokens refunded / Возвращено токенов",
  adminGrants: "Admin grants / Начислено админом",
  currentBalancesTotal: "Current balances total / Общий баланс пользователей",
  estimatedMargin: "Estimated margin / Примерная маржа",
  clientRevenue: "Client revenue / Доход от клиента",
  margin: "Margin / Маржа",
  payment: "Payment / Платеж",
  userFinance: "User Finance / Финансы пользователя",
  recentPayments: "Recent payments / Последние платежи",
  recentCreditTransactions: "Recent credit transactions / Последние транзакции",
  /** Moderation Center */
  moderation: "Moderation / Модерация",
  bannedWords: "Banned words / Запрещенные слова",
  blockedPatterns: "Blocked patterns / Заблокированные шаблоны",
  promptLength: "Prompt length / Длина prompt",
  nsfwBlock: "NSFW block / Блокировка NSFW",
  deepfakeBlock: "Deepfake block / Блокировка deepfake",
  illegalContent: "Illegal content / Незаконный контент",
  manualReview: "Manual review / Ручная проверка",
  allowed: "Allowed / Разрешено",
  blocked: "Blocked / Заблокировано",
  reason: "Reason / Причина",
  matchedText: "Matched text / Совпадение",
  /** Legal pages manager / Юридические страницы */
  legalPagesTitle: "Legal Pages / Юридические страницы",
  legalPagesDescription:
    "Public legal documents for QazCard AI. / Управление публичными юридическими документами QazCard AI.",
  legalPagesNav: "Legal Pages / Юридические страницы",
  legalTerms: "Terms of Service / Пользовательское соглашение",
  legalPrivacy: "Privacy Policy / Политика конфиденциальности",
  legalRefund: "Refund Policy / Политика возвратов",
  legalAiContent: "AI Content Policy / Политика AI-контента",
  legalCopyright: "Copyright Policy / Политика авторских прав",
  lpStatusDraft: "Draft / Черновик",
  lpStatusPublished: "Published / Опубликовано",
  lpVersion: "Version / Версия",
  lpPublish: "Publish / Опубликовать",
  lpPreview: "Preview / Предпросмотр",
  lpColPage: "Page / Страница",
  lpColSlug: "Slug / URL",
  lpColStatus: "Status / Статус",
  lpColVersion: "Version / Версия",
  lpColPublished: "Published at / Опубликовано",
  lpColUpdated: "Updated at / Обновлено",
  lpColActions: "Actions / Действия",
  lpView: "View / Смотреть (сайт)",
  lpEdit: "Edit / Редактировать",
  lpViewAdmin: "View / Смотреть (админ)",
  lpSeedDefaults: "Seed defaults / Создать страницы по умолчанию",
  lpEditorWarning: "Правовая оговорка / Legal",
  lpEditorWarningDesc:
    "Юридические тексты должны быть проверены юристом перед запуском сервиса. / Legal texts should be reviewed by counsel before service launch.",
  lpTitle: "Title / Название",
  lpUpdated: "Updated / Обновлено",
  lpViewOnly: "Только чтение (ADMIN) / Read-only (ADMIN)",
  lpToastDraftSaved: "Черновик сохранён / Draft saved",
  lpToastPublished: "Сохранено с публикацией / Saved as published",
  lpSaveDraft: "Save draft / Сохранить черновик",
  lpViewPublic: "View public page / Открыть публичную страницу",
  /** SEO Manager */
  seoPageTitle: "SEO / Лендинг и SEO",
  seoPageDescription:
    "Indexing, meta tags, landing ↔ app. / Настройки индексации, мета-тегов и связей между лендингом и приложением.",
  seoNav: "SEO / Лендинг и SEO",
  seoSectionLandingLinks: "Landing links / Ссылки лендинга",
  seoLandingCtaHint:
    "Если лендинг размещен отдельно, кнопки на лендинге должны вести в основное приложение: /login, /register, /dashboard/create/product-card.",
  seoSectionMetadata: "Metadata / Метаданные",
  seoSectionSearch: "Search engines / Поисковики",
  seoSectionRobots: "Robots and sitemap / Robots и sitemap",
  seoLabelLanding: "Landing URL / URL лендинга",
  seoLabelApp: "App URL / URL приложения",
  seoLabelTitle: "Title / Заголовок",
  seoLabelDescription: "Description / Описание",
  seoLabelKeywords: "Keywords / Ключевые слова",
  seoLabelCanonical: "Canonical URL / Канонический URL",
  seoLabelOg: "OpenGraph image / Изображение OpenGraph",
  seoLabelRobotsIndexing: "Robots indexing / Индексация robots.txt",
  seoLabelSitemap: "Sitemap URL / URL sitemap",
  seoLabelGoogle: "Google site verification / Подтверждение Google",
  seoLabelYandex: "Yandex verification / Подтверждение Яндекс",
  seoOpenRobots: "Open robots.txt",
  seoOpenSitemap: "Open sitemap.xml",
  seoSave: "Save / Сохранить",
  seoChecklistTitle: "Checklist / Чеклист",
  seoChecklistDesc: "Автопроверки и подсказки перед запуском.",
  seoIndexingOffTitle: "Индексация отключена",
  seoIndexingOffDesc:
    "Индексация отключена. Search engines получат Disallow: / в /robots.txt. Включите, когда подготовите публикацию.",
  /** Notifications & email templates */
  notifPageTitle: "Notifications / Уведомления",
  notifPageDescription: "Email provider, event toggles, and templates. / Провайдер, события и шаблоны писем.",
  notifNav: "Notifications / Уведомления",
  notifProviderSection: "Provider status / Статус провайдера",
  notifEventsSection: "Events / События",
  notifTemplatesSection: "Templates / Шаблоны",
  notifSmtpOk: "SMTP configured / SMTP настроен",
  notifSmtpNo: "SMTP not configured / SMTP не настроен",
  notifApiOk: "API key configured / API-ключ настроен",
  notifApiNo: "API key not set / API-ключ не задан",
  notifTestEmail: "Send test / Отправить тест",
  notifLabelEmailFrom: "Email from / Отправитель",
  passwordResetTemplate:
    "Password reset / Восстановление пароля",
  notifTemplateEditor: "Template editor / Редактор шаблона",
  notifSaveSettings: "Save settings / Сохранить настройки",
  notifSeed: "Seed defaults / Создать шаблоны по умолчанию",
  notifReadOnly: "Read-only (ADMIN) / Только чтение (ADMIN)",
} as const;

export type AdminTermKey = keyof typeof ADMIN_TERM_LABELS;

export function adminTerm(key: AdminTermKey): string {
  return ADMIN_TERM_LABELS[key];
}
