import type { AppSettingTypeName } from "@/lib/app-setting-value";
import { CARD_BUILDER_PROMPTS_DEFAULTS } from "@/config/card-builder-prompts-defaults";
import { DEFAULT_PRODUCT_CARD_WEB_RESEARCH_SETTINGS } from "@/lib/product-card-web-research-config";

export type AppSettingGroupId =
  | "general"
  | "credits"
  | "generation"
  | "uploads"
  | "productCard"
  | "classifier"
  | "maintenance"
  | "seo"
  | "moderation"
  | "notifications";

export type AppSettingRegistryEntry = {
  key: string;
  group: AppSettingGroupId;
  label: string;
  description: string;
  type: AppSettingTypeName;
  defaultValue: unknown;
  editable: boolean;
  sensitive: boolean;
};

export const APP_SETTING_GROUPS: { id: AppSettingGroupId; label: string }[] = [
  { id: "general", label: "General / Общие" },
  { id: "credits", label: "Credits / Токены" },
  { id: "generation", label: "Generation / Генерации" },
  { id: "uploads", label: "Uploads / Загрузки" },
  { id: "productCard", label: "Product Card / Карточка товара" },
  { id: "classifier", label: "Classifier / Классификатор" },
  { id: "maintenance", label: "Maintenance / Техобслуживание" },
  { id: "seo", label: "SEO / Лендинг и SEO" },
  { id: "moderation", label: "Moderation / Модерация" },
  { id: "notifications", label: "Notifications / Уведомления" },
];

export const APP_SETTINGS_REGISTRY: AppSettingRegistryEntry[] = [
  {
    key: "APP_NAME",
    group: "general",
    label: "APP_NAME / Название приложения",
    description: "Название приложения.",
    type: "string",
    defaultValue: "QazCard AI",
    editable: true,
    sensitive: false,
  },
  {
    key: "SUPPORT_EMAIL",
    group: "general",
    label: "SUPPORT_EMAIL / Email поддержки",
    description: "Email поддержки.",
    type: "string",
    defaultValue: "support@qazcard.ai",
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_CURRENCY",
    group: "general",
    label: "DEFAULT_CURRENCY / Основная валюта",
    description: "Основная валюта сервиса.",
    type: "string",
    defaultValue: "KZT",
    editable: true,
    sensitive: false,
  },
  {
    key: "FREE_CREDITS_FOR_NEW_USERS",
    group: "credits",
    label: "FREE_CREDITS_FOR_NEW_USERS / Бесплатные токены новым пользователям",
    description: "Сколько токенов начислять новым пользователям.",
    type: "number",
    defaultValue: 0,
    editable: true,
    sensitive: false,
  },
  {
    key: "DASHBOARD_SUBSCRIPTION_PLAN_UI_ENABLED",
    group: "credits",
    label: "DASHBOARD_SUBSCRIPTION_PLAN_UI_ENABLED / Блок «Тариф» в кабинете",
    description:
      "Показывать карточку «Тариф» (подписка) на странице /dashboard. По умолчанию выключено — тарифы пока не реализованы.",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "TOKEN_VALUE_KZT",
    group: "credits",
    label: "TOKEN_VALUE_KZT / Стоимость токена в ₸",
    description: "Стоимость одного внутреннего токена в тенге.",
    type: "number",
    defaultValue: 10,
    editable: true,
    sensitive: false,
  },
  {
    key: "USD_TO_KZT",
    group: "credits",
    label: "USD_TO_KZT / Курс USD/KZT",
    description: "Курс USD/KZT для расчетов себестоимости.",
    type: "number",
    defaultValue: 500,
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_MARKUP_PERCENT",
    group: "credits",
    label: "DEFAULT_MARKUP_PERCENT / Наценка по умолчанию %",
    description: "Наценка по умолчанию для пересчета себестоимости в токены.",
    type: "number",
    defaultValue: 40,
    editable: true,
    sensitive: false,
  },
  {
    key: "LOW_BALANCE_THRESHOLD",
    group: "credits",
    label: "LOW_BALANCE_THRESHOLD / Порог низкого баланса",
    description: "Порог низкого баланса пользователя.",
    type: "number",
    defaultValue: 50,
    editable: true,
    sensitive: false,
  },
  {
    key: "KASPI_MANUAL_SETTINGS",
    group: "credits",
    label: "KASPI_MANUAL_SETTINGS / Ручной перевод Kaspi",
    description:
      "Временный сценарий: пользователь переводит на Kaspi по инструкции, отправляет чек в WhatsApp, админ подтверждает вручную. JSON: kaspiManualEnabled, recipientName, recipientPhone, instructionText, requireReceiptUpload, paymentCodePrefix, expiresMinutes, whatsappEnabled, whatsappPhone, whatsappMessageTemplate.",
    type: "json",
    defaultValue: {
      kaspiManualEnabled: false,
      recipientName: "QazCard AI",
      recipientPhone: "+7XXXXXXXXXX",
      instructionText:
        "Переведите сумму на Kaspi, укажите код заявки в комментарии и отправьте чек в WhatsApp.",
      requireReceiptUpload: false,
      paymentCodePrefix: "QAZCARD",
      expiresMinutes: 1440,
      whatsappEnabled: true,
      whatsappPhone: "77001234567",
      whatsappMessageTemplate:
        "Здравствуйте! Я оплатил пополнение QazCard AI.\\n\\nКод заявки: {{paymentCode}}\\nПакет: {{packageLabel}}\\nСумма: {{amountKzt}} ₸\\nТокены: {{creditsAmount}}\\nАккаунт: {{userEmail}}\\n\\nПрикрепляю чек.",
    },
    editable: true,
    sensitive: false,
  },
  {
    key: "MAX_ACTIVE_GENERATIONS_PER_USER",
    group: "generation",
    label: "MAX_ACTIVE_GENERATIONS_PER_USER / Макс. активных генераций",
    description: "Максимум активных генераций на одного пользователя.",
    type: "number",
    defaultValue: 3,
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_IMAGE_MODEL_SLUG",
    group: "generation",
    label: "DEFAULT_IMAGE_MODEL_SLUG / Модель изображения по умолчанию",
    description: "Модель изображения по умолчанию (slug).",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_VIDEO_MODEL_SLUG",
    group: "generation",
    label: "DEFAULT_VIDEO_MODEL_SLUG / Модель видео по умолчанию",
    description: "Модель видео по умолчанию (slug).",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_PRODUCT_CONCEPT_IMAGE_MODEL_SLUG",
    group: "generation",
    label: "DEFAULT_PRODUCT_CONCEPT_IMAGE_MODEL_SLUG / Модель фото с концепциями",
    description: "Модель по умолчанию для фото с концепциями.",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_MARKETPLACE_CARD_MODEL_SLUG",
    group: "generation",
    label: "DEFAULT_MARKETPLACE_CARD_MODEL_SLUG / Модель карточки товара",
    description: "Модель по умолчанию для карточки товара.",
    type: "string",
    defaultValue: "gpt-image-2-image-to-image",
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_PRODUCT_VIDEO_MODEL_SLUG",
    group: "generation",
    label: "DEFAULT_PRODUCT_VIDEO_MODEL_SLUG / Модель видео товара по умолчанию",
    description: "Модель по умолчанию для видео товара.",
    type: "string",
    defaultValue: "seedance-2-0-fast",
    editable: true,
    sensitive: false,
  },
  {
    key: "GENERATION_TIMEOUT_MINUTES",
    group: "generation",
    label: "GENERATION_TIMEOUT_MINUTES / Таймаут генерации, мин",
    description: "Через сколько минут считать генерацию зависшей.",
    type: "number",
    defaultValue: 30,
    editable: true,
    sensitive: false,
  },
  {
    key: "MAX_IMAGE_UPLOAD_MB",
    group: "uploads",
    label: "MAX_IMAGE_UPLOAD_MB / Макс. размер изображения, МБ",
    description: "Максимальный размер загружаемого изображения.",
    type: "number",
    defaultValue: 10,
    editable: true,
    sensitive: false,
  },
  {
    key: "MAX_VIDEO_UPLOAD_MB",
    group: "uploads",
    label: "MAX_VIDEO_UPLOAD_MB / Макс. размер видео, МБ",
    description: "Максимальный размер загружаемого видео.",
    type: "number",
    defaultValue: 100,
    editable: true,
    sensitive: false,
  },
  {
    key: "MAX_AUDIO_UPLOAD_MB",
    group: "uploads",
    label: "MAX_AUDIO_UPLOAD_MB / Макс. размер аудио, МБ",
    description: "Максимальный размер загружаемого аудио.",
    type: "number",
    defaultValue: 50,
    editable: true,
    sensitive: false,
  },
  {
    key: "ALLOWED_IMAGE_MIME_TYPES",
    group: "uploads",
    label: "ALLOWED_IMAGE_MIME_TYPES / Разрешённые MIME изображений",
    description: "Список MIME-типов для изображений (JSON array).",
    type: "json",
    defaultValue: ["image/jpeg", "image/png", "image/webp"],
    editable: true,
    sensitive: false,
  },
  {
    key: "ALLOWED_VIDEO_MIME_TYPES",
    group: "uploads",
    label: "ALLOWED_VIDEO_MIME_TYPES / Разрешённые MIME видео",
    description: "Список MIME-типов для видео (JSON array).",
    type: "json",
    defaultValue: ["video/mp4", "video/quicktime", "video/webm"],
    editable: true,
    sensitive: false,
  },
  {
    key: "ALLOWED_AUDIO_MIME_TYPES",
    group: "uploads",
    label: "ALLOWED_AUDIO_MIME_TYPES / Разрешённые MIME аудио",
    description: "Список MIME-типов для аудио (JSON array).",
    type: "json",
    defaultValue: ["audio/mpeg", "audio/wav", "audio/mp4"],
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_ENABLED",
    group: "productCard",
    label: "PRODUCT_CARD_ENABLED / Раздел карточки товара",
    description: "Включить раздел «Создать карточку товара».",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MAX_SOURCE_IMAGES",
    group: "productCard",
    label: "PRODUCT_CARD_MAX_SOURCE_IMAGES / Макс. фото товара",
    description: "Максимальное число исходных фото товара в Product Card flow.",
    type: "number",
    defaultValue: 4,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_REQUIRED_MAIN_IMAGE",
    group: "productCard",
    label: "PRODUCT_CARD_REQUIRED_MAIN_IMAGE / Главное фото обязательно",
    description: "Требовать главное фото товара.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_ALLOWED_IMAGE_MIME_TYPES",
    group: "productCard",
    label: "PRODUCT_CARD_ALLOWED_IMAGE_MIME_TYPES / MIME фото товара",
    description: "Разрешенные MIME-типы исходных фото товара.",
    type: "json",
    defaultValue: ["image/jpeg", "image/png", "image/webp"],
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MAX_IMAGE_UPLOAD_MB",
    group: "productCard",
    label: "PRODUCT_CARD_MAX_IMAGE_UPLOAD_MB / Макс. размер фото, МБ",
    description: "Максимальный размер исходного фото товара.",
    type: "number",
    defaultValue: 10,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_CLASSIFIER_MODEL_SLUG",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_CLASSIFIER_MODEL_SLUG / Классификатор",
    description: "Product Card модель классификации по умолчанию.",
    type: "string",
    defaultValue: "gemini-2-5-flash-classifier",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_CONCEPT_IMAGE_MODEL_SLUG",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_CONCEPT_IMAGE_MODEL_SLUG / Фото с концепциями",
    description: "Product Card IMAGE модель для фото с концепциями.",
    type: "string",
    defaultValue: "seedream-4-0-product-concept",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_MARKETPLACE_CARD_MODEL_SLUG",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_MARKETPLACE_CARD_MODEL_SLUG / Карточка товара",
    description: "Product Card IMAGE модель для карточки товара.",
    type: "string",
    defaultValue: "gpt-image-2-product-card",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_CARD_BUILDER_MODEL_SLUG",
    group: "productCard",
    label: "Модель «Создать карточку» (slug)",
    description:
      "IMAGE-модель scope PRODUCT_CARD с типом PRODUCT_CARD_BUILDER. Пустое значение — fallback на карточку маркетплейса.",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_SCENARIOS",
    group: "productCard",
    label: "Сценарии AI-карточек товара",
    description: "Переключатели вкладок: фото с концепциями, карточка для маркетплейса, «Создать карточку», видео товара.",
    type: "json",
    defaultValue: {
      conceptPhoto: { enabled: true, label: "Фото с концепциями" },
      marketplaceCard: { enabled: true, label: "Карточка для маркетплейса" },
      cardBuilder: { enabled: true, label: "Создать карточку" },
      productVideo: { enabled: true, label: "Видео товара" },
    },
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_BUILDER_PLAN_CREDITS",
    group: "productCard",
    label: "[Legacy] Мастер: стоимость «структура» (токены)",
    description: "Устарело. Runtime не читает. Каноничный источник — PRODUCT_CARD_CARD_BUILDER_PRICING или /admin/pricing → Создать карточку.",
    type: "number",
    defaultValue: 0,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_BUILDER_SLIDE_CREDITS",
    group: "productCard",
    label: "[Legacy] Мастер: один слайд (токены)",
    description: "Устарело. Runtime не читает. Каноничный источник — PRODUCT_CARD_CARD_BUILDER_PRICING.",
    type: "number",
    defaultValue: 150,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_BUILDER_GALLERY_6_CREDITS",
    group: "productCard",
    label: "[Legacy] Мастер: галерея из 6 (токены)",
    description: "Устарело. Runtime не читает. Каноничный источник — PRODUCT_CARD_CARD_BUILDER_PRICING.",
    type: "number",
    defaultValue: 750,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_BUILDER_GALLERY_8_CREDITS",
    group: "productCard",
    label: "[Legacy] Мастер: галерея из 8 (токены)",
    description: "Устарело. Runtime не читает. Каноничный источник — PRODUCT_CARD_CARD_BUILDER_PRICING.",
    type: "number",
    defaultValue: 950,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_BUILDER_PRICE_MULTIPLIERS",
    group: "productCard",
    label: "[Legacy] Мастер: множители цены",
    description: "Устарело. Runtime не читает. Каноничный источник — PRODUCT_CARD_CARD_BUILDER_PRICING.",
    type: "json",
    defaultValue: {
      premiumStyle: 1.2,
      heavyTextInfographic: 1.1,
    },
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_VIDEO_MODEL_SLUG",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_VIDEO_MODEL_SLUG / Видео товара",
    description: "Product Card VIDEO модель по умолчанию.",
    type: "string",
    defaultValue: "seedance-2-0-fast-product-video",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_USD_TO_KZT",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_USD_TO_KZT / Курс USD/KZT",
    description: "Курс USD/KZT только для Product Card pricing.",
    type: "number",
    defaultValue: 500,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_TOKEN_VALUE_KZT",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_TOKEN_VALUE_KZT / Цена токена",
    description: "Стоимость внутреннего токена в тенге только для Product Card.",
    type: "number",
    defaultValue: 10,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_DEFAULT_MARKUP_PERCENT",
    group: "productCard",
    label: "PRODUCT_CARD_DEFAULT_MARKUP_PERCENT / Наценка Product Card",
    description: "Наценка по умолчанию для Product Card pricing.",
    type: "number",
    defaultValue: 100,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_ALLOW_NEGATIVE_MARGIN",
    group: "productCard",
    label: "PRODUCT_CARD_ALLOW_NEGATIVE_MARGIN / Разрешить минусовую маржу",
    description: "Разрешать сохранять Product Card цену ниже себестоимости.",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_LOW_MARGIN_WARNING_PERCENT",
    group: "productCard",
    label: "PRODUCT_CARD_LOW_MARGIN_WARNING_PERCENT / Warning маржи",
    description: "Порог предупреждения по марже Product Card.",
    type: "number",
    defaultValue: 30,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MIN_CONCEPT_IMAGE_TOKENS",
    group: "productCard",
    label: "PRODUCT_CARD_MIN_CONCEPT_IMAGE_TOKENS / Мин. фото с концепцией",
    description: "Минимум токенов для Product Card concept photo.",
    type: "number",
    defaultValue: 15,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MIN_MARKETPLACE_CARD_TOKENS",
    group: "productCard",
    label: "PRODUCT_CARD_MIN_MARKETPLACE_CARD_TOKENS / Мин. карточка",
    description: "Минимум токенов для Product Card marketplace card.",
    type: "number",
    defaultValue: 25,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MIN_VIDEO_TOKENS",
    group: "productCard",
    label: "PRODUCT_CARD_MIN_VIDEO_TOKENS / Мин. видео",
    description: "Минимум токенов для Product Card video.",
    type: "number",
    defaultValue: 40,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_CONCEPT_IMAGE_SIZES",
    group: "productCard",
    label: "PRODUCT_CARD_CONCEPT_IMAGE_SIZES / Размеры фото с концепциями",
    description: "Preset размеров для Product Card concept photo.",
    type: "json",
    defaultValue: [
      { id: "1x1", label: "1:1 1024x1024", width: 1024, height: 1024, aspectRatio: "1:1" },
      { id: "4x3", label: "4:3 1200x900", width: 1200, height: 900, aspectRatio: "4:3" },
      { id: "3x4", label: "3:4 1200x1600", width: 1200, height: 1600, aspectRatio: "3:4" },
      { id: "16x9", label: "16:9 1344x768", width: 1344, height: 768, aspectRatio: "16:9" },
      { id: "9x16", label: "9:16 768x1344", width: 768, height: 1344, aspectRatio: "9:16" }
    ],
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MARKETPLACE_CARD_SIZES",
    group: "productCard",
    label: "PRODUCT_CARD_MARKETPLACE_CARD_SIZES / Размеры карточки",
    description: "Preset размеров для marketplace card.",
    type: "json",
    defaultValue: [
      { id: "square", label: "Квадрат 1000x1000", width: 1000, height: 1000, aspectRatio: "1:1" },
      { id: "marketplace_vertical", label: "Вертикальная 1200x1600", width: 1200, height: 1600, aspectRatio: "3:4" },
      { id: "story", label: "Story 1080x1920", width: 1080, height: 1920, aspectRatio: "9:16" },
      { id: "banner", label: "Баннер 1200x628", width: 1200, height: 628, aspectRatio: "1.91:1" }
    ],
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_VIDEO_PRESETS",
    group: "productCard",
    label: "PRODUCT_CARD_VIDEO_PRESETS / Видео presets",
    description: "Preset длительности, разрешения и aspect ratio для Product Card video.",
    type: "json",
    defaultValue: [
      { duration: 5, resolution: "720p", aspectRatio: "1:1" },
      { duration: 10, resolution: "720p", aspectRatio: "1:1" },
      { duration: 5, resolution: "1080p", aspectRatio: "9:16" },
      { duration: 10, resolution: "1080p", aspectRatio: "9:16" }
    ],
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MOCK_MODE",
    group: "productCard",
    label: "PRODUCT_CARD_MOCK_MODE / Тестовый режим карточек",
    description: "Тестовый режим карточек товара.",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "DEFAULT_PRODUCT_CARD_CATEGORY",
    group: "productCard",
    label: "DEFAULT_PRODUCT_CARD_CATEGORY / Категория по умолчанию",
    description: "Категория товара по умолчанию.",
    type: "string",
    defaultValue: "other",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_ALLOW_MANUAL_CATEGORY",
    group: "productCard",
    label: "PRODUCT_CARD_ALLOW_MANUAL_CATEGORY / Ручной выбор категории",
    description: "Разрешить пользователю менять категорию вручную.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_MAX_USER_PROMPT_LENGTH",
    group: "productCard",
    label: "PRODUCT_CARD_MAX_USER_PROMPT_LENGTH / Макс. длина prompt",
    description: "Максимальная длина дополнительного prompt пользователя.",
    type: "number",
    defaultValue: 1000,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_CARD_BUILDER_PRICING",
    group: "productCard",
    label: "Тарифы «Создать карточку»",
    description:
      "Каноничный JSON тарифов card_builder. Рекомендуется редактировать в /admin/pricing → вкладка «Создать карточку».",
    type: "json",
    defaultValue: {
      cardBuilderPlanCredits: 0,
      cardBuilderSingleSlideCredits: 150,
      cardBuilderGallery6Credits: 750,
      cardBuilderGallery8Credits: 950,
      multipliers: { premiumStyle: 1.2, heavyTextInfographic: 1.1 },
    },
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_CARD_BUILDER_PROMPTS",
    group: "productCard",
    label: "PRODUCT_CARD_CARD_BUILDER_PROMPTS / Промпты «Создать карточку»",
    description:
      "JSON-набор промптов card_builder (vision, slide base, category/cardType/template, text lock, negative rules). Редактируется в /admin/product-card.",
    type: "json",
    defaultValue: CARD_BUILDER_PROMPTS_DEFAULTS,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CARD_WEB_RESEARCH_SETTINGS",
    group: "productCard",
    label: "PRODUCT_CARD_WEB_RESEARCH_SETTINGS / Web Research характеристик",
    description:
      "Настройки поиска характеристик товара в интернете для card_builder (Tavily). Редактируется в /admin/product-card → Advanced.",
    type: "json",
    defaultValue: DEFAULT_PRODUCT_CARD_WEB_RESEARCH_SETTINGS,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CLASSIFIER_PROVIDER",
    group: "classifier",
    label: "PRODUCT_CLASSIFIER_PROVIDER / Провайдер классификатора товара",
    description: "Провайдер: mock, openai, gemini. API keys только в env.",
    type: "string",
    defaultValue: "mock",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CLASSIFIER_MODEL",
    group: "classifier",
    label: "PRODUCT_CLASSIFIER_MODEL / Модель классификатора",
    description: "Модель классификатора (имя/alias).",
    type: "string",
    defaultValue: "mock",
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CLASSIFIER_CONFIDENCE_THRESHOLD",
    group: "classifier",
    label: "PRODUCT_CLASSIFIER_CONFIDENCE_THRESHOLD / Порог уверенности",
    description: "Минимальная уверенность для автоматического выбора категории (0..1).",
    type: "number",
    defaultValue: 0.6,
    editable: true,
    sensitive: false,
  },
  {
    key: "PRODUCT_CLASSIFIER_FALLBACK_CATEGORY",
    group: "classifier",
    label: "PRODUCT_CLASSIFIER_FALLBACK_CATEGORY / Категория при сомнении",
    description: "Категория по умолчанию, если классификатор не уверен.",
    type: "string",
    defaultValue: "other",
    editable: true,
    sensitive: false,
  },
  {
    key: "MAINTENANCE_MODE",
    group: "maintenance",
    label: "MAINTENANCE_MODE / Режим техобслуживания",
    description: "Режим технического обслуживания.",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "MAINTENANCE_MESSAGE",
    group: "maintenance",
    label: "MAINTENANCE_MESSAGE / Сообщение при техработах",
    description: "Текст для пользователей при техобслуживании.",
    type: "string",
    defaultValue: "Сервис временно недоступен. Мы скоро вернемся.",
    editable: true,
    sensitive: false,
  },
  {
    key: "ALLOW_ADMIN_DURING_MAINTENANCE",
    group: "maintenance",
    label: "ALLOW_ADMIN_DURING_MAINTENANCE / Админы при техработах",
    description: "Разрешить админам входить во время техобслуживания.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "LANDING_URL",
    group: "seo",
    label: "LANDING_URL / URL лендинга",
    description: "URL отдельного SEO-лендинга.",
    type: "string",
    defaultValue: "https://qazcard.ai",
    editable: true,
    sensitive: false,
  },
  {
    key: "APP_URL",
    group: "seo",
    label: "APP_URL / URL приложения",
    description: "URL основного приложения.",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "SEO_DEFAULT_TITLE",
    group: "seo",
    label: "SEO_DEFAULT_TITLE / SEO title по умолчанию",
    description: "Заголовок по умолчанию для meta.",
    type: "string",
    defaultValue:
      "QazCard AI — AI карточки товаров, фото и видео для маркетплейсов",
    editable: true,
    sensitive: false,
  },
  {
    key: "SEO_DEFAULT_DESCRIPTION",
    group: "seo",
    label: "SEO_DEFAULT_DESCRIPTION / SEO description",
    description: "Описание по умолчанию для meta.",
    type: "string",
    defaultValue:
      "Создавайте карточки товаров, фото и короткие видео с помощью AI.",
    editable: true,
    sensitive: false,
  },
  {
    key: "SEO_DEFAULT_KEYWORDS",
    group: "seo",
    label: "SEO_DEFAULT_KEYWORDS / Ключевые слова (JSON)",
    description: "Массив ключевых слов для meta keywords.",
    type: "json",
    defaultValue: [
      "AI карточки товаров",
      "создать карточку товара",
      "генератор карточек товаров",
      "AI фото товара",
      "AI видео товара",
      "карточка товара для маркетплейса",
      "QazCard AI",
    ],
    editable: true,
    sensitive: false,
  },
  {
    key: "SEO_CANONICAL_URL",
    group: "seo",
    label: "SEO_CANONICAL_URL / Канонический URL",
    description: "Канонический URL сайта (главной публичной витрины).",
    type: "string",
    defaultValue: "https://qazcard.ai/",
    editable: true,
    sensitive: false,
  },
  {
    key: "OG_IMAGE_URL",
    group: "seo",
    label: "OG_IMAGE_URL / OpenGraph изображение",
    description: "URL изображения для OpenGraph.",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "ROBOTS_INDEXING_ENABLED",
    group: "seo",
    label: "ROBOTS_INDEXING_ENABLED / Индексация robots",
    description: "Разрешить индексацию сайта поисковиками.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "SITEMAP_URL",
    group: "seo",
    label: "SITEMAP_URL / URL sitemap",
    description: "Полный URL карты сайта (для robots.txt).",
    type: "string",
    defaultValue: "https://qazcard.ai/sitemap.xml",
    editable: true,
    sensitive: false,
  },
  {
    key: "YANDEX_VERIFICATION",
    group: "seo",
    label: "YANDEX_VERIFICATION / Яндекс.Вебмастер",
    description: "Код подтверждения Яндекс.Вебмастер.",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "GOOGLE_SITE_VERIFICATION",
    group: "seo",
    label: "GOOGLE_SITE_VERIFICATION / Google Search Console",
    description: "Код подтверждения Google Search Console.",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_ENABLED",
    group: "moderation",
    label: "MODERATION_ENABLED / Включить модерацию",
    description: "Включить проверку prompt перед генерацией.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_BANNED_WORDS",
    group: "moderation",
    label: "MODERATION_BANNED_WORDS / Запрещённые слова",
    description: "Список запрещённых слов и фраз (JSON array).",
    type: "json",
    defaultValue: [],
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_BLOCKED_PATTERNS",
    group: "moderation",
    label: "MODERATION_BLOCKED_PATTERNS / Regex-шаблоны",
    description: "Список регулярных выражений (JSON array строк, флаги — через /pattern/i отдельно нельзя; используйте встроенный i).",
    type: "json",
    defaultValue: [],
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_MAX_PROMPT_LENGTH",
    group: "moderation",
    label: "MODERATION_MAX_PROMPT_LENGTH / Макс. длина prompt",
    description: "Максимальная длина основного prompt (символы).",
    type: "number",
    defaultValue: 2000,
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_BLOCK_NSFW",
    group: "moderation",
    label: "MODERATION_BLOCK_NSFW / NSFW",
    description: "Блокировать NSFW-запросы (ключевые слова).",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_BLOCK_DEEPFAKE",
    group: "moderation",
    label: "MODERATION_BLOCK_DEEPFAKE / Deepfake",
    description: "Блокировать deepfake/имитацию реальных людей.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_BLOCK_MINORS",
    group: "moderation",
    label: "MODERATION_BLOCK_MINORS / Несовершеннолетние",
    description: "Блокировать небезопасный контент, связанный с несовершеннолетними.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_BLOCK_ILLEGAL",
    group: "moderation",
    label: "MODERATION_BLOCK_ILLEGAL / Незаконный контент",
    description: "Блокировать незаконный контент (ключевые фразы).",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "MODERATION_REVIEW_MODE",
    group: "moderation",
    label: "MODERATION_REVIEW_MODE / Ручная проверка",
    description: "Все запросы отклоняются до ручного разбора (MVP: блок).",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "EMAIL_PROVIDER",
    group: "notifications",
    label: "EMAIL_PROVIDER / Провайдер email",
    description: "Провайдер email: none, smtp, resend, sendgrid. Секреты — только в env.",
    type: "string",
    defaultValue: "none",
    editable: true,
    sensitive: false,
  },
  {
    key: "EMAIL_FROM",
    group: "notifications",
    label: "EMAIL_FROM / Отправитель",
    description: "Адрес и имя From для писем (если не задано в env).",
    type: "string",
    defaultValue: "QazCard AI <noreply@qazcard.ai>",
    editable: true,
    sensitive: false,
  },
  {
    key: "EMAIL_ENABLED",
    group: "notifications",
    label: "EMAIL_ENABLED / Отправка email",
    description: "Глобально включить доставку писем (при настроенном провайдере).",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_WELCOME_EMAIL",
    group: "notifications",
    label: "SEND_WELCOME_EMAIL / Письмо при регистрации",
    description: "Отправлять WELCOME_USER после регистрации.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_PAYMENT_SUCCESS_EMAIL",
    group: "notifications",
    label: "SEND_PAYMENT_SUCCESS_EMAIL / Успешная оплата",
    description: "Отправлять PAYMENT_SUCCESS при начислении пакета.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_GENERATION_COMPLETED_EMAIL",
    group: "notifications",
    label: "SEND_GENERATION_COMPLETED_EMAIL / Генерация готова",
    description: "Письмо при COMPLETED.",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_GENERATION_FAILED_EMAIL",
    group: "notifications",
    label: "SEND_GENERATION_FAILED_EMAIL / Ошибка генерации",
    description: "Письмо при FAILED.",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_LOW_BALANCE_EMAIL",
    group: "notifications",
    label: "SEND_LOW_BALANCE_EMAIL / Низкий баланс",
    description: "Писать, если баланс ниже LOW_BALANCE_THRESHOLD (с анти-спам).",
    type: "boolean",
    defaultValue: false,
    editable: true,
    sensitive: false,
  },
  {
    key: "ADMIN_ALERT_EMAIL",
    group: "notifications",
    label: "ADMIN_ALERT_EMAIL / Email для алертов",
    description: "Куда слать письма об ошибках провайдера/воркера (без рассылки пользователям).",
    type: "string",
    defaultValue: "",
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_ADMIN_PROVIDER_ERRORS",
    group: "notifications",
    label: "SEND_ADMIN_PROVIDER_ERRORS / Алерты провайдера",
    description: "Уведомлять при неудачной проверке Kie (из админки).",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
  {
    key: "SEND_ADMIN_WORKER_ERRORS",
    group: "notifications",
    label: "SEND_ADMIN_WORKER_ERRORS / Алерты worker",
    description: "Уведомлять при окончательном падении job в очереди.",
    type: "boolean",
    defaultValue: true,
    editable: true,
    sensitive: false,
  },
];

const REGISTRY_BY_KEY = new Map(
  APP_SETTINGS_REGISTRY.map((e) => [e.key, e] as const),
);

export function getRegistryEntry(key: string): AppSettingRegistryEntry | undefined {
  return REGISTRY_BY_KEY.get(key);
}

export function getAllRegistryKeys(): string[] {
  return APP_SETTINGS_REGISTRY.map((e) => e.key);
}

export const REGISTRY_KEY_SET: ReadonlySet<string> = new Set(
  APP_SETTINGS_REGISTRY.map((e) => e.key),
);
